import { expect, test } from "@playwright/test"

test("optional Data Analysis calculates, saves and recovers in its own Workspace", async ({ page }) => {
  test.setTimeout(90_000)
  await page.goto("/")
  await expect(page.locator('[data-testid="new-chat-button"]')).toBeVisible()
  const response = await page.request.post("/api/sessions", { data: { title: "Analysis E2E" } })
  expect(response.ok()).toBe(true)
  const { id } = await response.json()
  const upload = await page.request.post(`/api/sessions/${id}/files`, {
    multipart: { files: { name: "sales.csv", mimeType: "text/csv",
      buffer: Buffer.from("region,sales\nEast,10\nWest,20\nEast,30\n") } },
  })
  expect(upload.ok()).toBe(true)
  await page.goto(`/chat/${id}`)
  const workspace = page.locator('[data-testid="workspace-panel"]')
  await workspace.getByRole("button", { name: "extensions", exact: true }).click()
  const toggle = page.locator('[data-testid="workspace-tool-analyze_data"]')
  await expect(toggle).not.toBeChecked()
  await toggle.check()
  await expect(toggle).toBeChecked()
  await workspace.getByTestId("workspace-tab-analysis").click()
  await page.locator('[data-testid="analysis-action"]').selectOption("chart")
  await page.locator('[data-testid="analysis-x"]').fill("region")
  await page.locator('[data-testid="analysis-y"]').fill("sales")
  await page.locator('[data-testid="run-analysis"]').click()
  const result = page.locator('[data-testid="analysis-result"]')
  await expect(result).toContainText("East", { timeout: 40_000 })
  await expect(result).toContainText("40")
  await expect(result.locator("img")).toBeVisible()
  await expect.poll(() => result.locator("img").evaluate((img: HTMLImageElement) => img.naturalWidth))
    .toBeGreaterThan(0)
  await result.locator('[data-testid="save-analysis"]').click()
  await expect(result).toContainText("Saved to Workspace")
  const files = await (await page.request.get(`/api/sessions/${id}/files`)).json()
  expect(files.files.filter((file: any) => file.logical_path.startsWith("artifacts/analysis/")))
    .toHaveLength(4)
  await page.reload()
  await workspace.getByTestId("workspace-tab-analysis").click()
  await expect(result).toContainText("Source 3 rows")
  const other = await (await page.request.post("/api/sessions", { data: { title: "Other" } })).json()
  const selection = await (await page.request.get(`/api/workspaces/${other.id}/extensions`)).json()
  expect(selection.selected_tool_names).toEqual([])
})
