import { test, expect } from "@playwright/test"

test.use({ storageState: { cookies: [], origins: [] } })

test("password change requires confirmation and signs out all old logins", async ({ page }, testInfo) => {
  await page.goto("/")
  await page.getByTestId("login-name").fill("password-user")
  await page.getByTestId("login-password").fill("initial-test-password")
  await page.getByTestId("login-submit").click()
  await page.getByTestId("change-password-button").click()
  const dialog = page.getByRole("dialog")
  await expect(dialog).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath("password-dialog.png") })
  await dialog.getByLabel("Current password", { exact: true }).fill("initial-test-password")
  await dialog.getByLabel("New password", { exact: true }).fill("changed-test-password")
  await dialog.getByLabel("Confirm new password", { exact: true }).fill("mismatch-test-password")
  await dialog.getByRole("button", { name: "Change password and sign out" }).click()
  await expect(dialog.getByRole("alert")).toHaveText("New passwords do not match.")
  await dialog.getByLabel("Confirm new password", { exact: true }).fill("changed-test-password")
  await dialog.getByRole("button", { name: "Change password and sign out" }).click()
  await expect(page.getByTestId("login-form")).toBeVisible()
  await page.getByTestId("login-name").fill("password-user")
  await page.getByTestId("login-password").fill("initial-test-password")
  await page.getByTestId("login-submit").click()
  await expect(page.getByRole("alert")).toContainText("Invalid username or password")
  await page.getByTestId("login-password").fill("changed-test-password")
  await page.getByTestId("login-submit").click()
  await expect(page.getByTestId("change-password-button")).toBeVisible()
})
