"""PypdfParser + PdfParser contract tests (P2-R2-A2).

Per P2-R2-A §21.B-E + §22 (no Mock for core paths):

- B. Models / Protocol (immutability, 1-based page, no abs path leak, no
  pypdf object leak, Protocol shape)
- C. Inspect (single/multi/blank/encrypted/corrupted/nonexistent/dir,
  metadata safety, file handle release, idempotent)
- D. Extract (single/multi/order/None text/CRLF/NUL/blank/encrypted/
  corrupted/page-failure/handle release/idempotent/no source mutation/
  close idempotent)
- E. Security / Boundary (no network / OCR / model / LLM / Provider /
  abs-path leak / raw exception leak / DB write / FastAPI dep /
  KnowledgeService dep / Markdown / page marker / upload API / Tool)

Mock only for: forcing page extract exception, simulating pypdf missing,
verifying safe error mapping, verifying single-page failure semantics.

All PDFs are generated by ``tests/_pdf_fixture_factory.py`` (offline,
deterministic, project-generated, no copyrighted content).
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest

from pi_agent_core_py.web.knowledge.pdf_parser import (
    MAX_METADATA_VALUE_LENGTH,
    TEXT_ESTIMATE_MIN_CHARS_PER_PAGE,
    TEXT_ESTIMATE_SAMPLE_COUNT,
    InvalidPdf,
    PdfFileNotFound,
    PdfInspection,
    PdfMetadata,
    PdfNotAFile,
    PdfPage,
    PdfPageExtractFailed,
    PdfParser,
    PdfParserError,
    PdfParserUnavailable,
    PdfPasswordRequired,
    truncate_metadata_value,
)
from pi_agent_core_py.web.knowledge.pypdf_parser import PypdfParser
from tests._pdf_fixture_factory import (
    file_sha256,
    write_blank_pdf,
    write_corrupted_pdf,
    write_encrypted_pdf,
    write_text_pdf,
)

# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture
def parser():
    p = PypdfParser()
    yield p
    p.close()


@pytest.fixture
def text_pdf(tmp_path):
    path = tmp_path / "text.pdf"
    write_text_pdf(
        path,
        pages=["Hello World page 1", "Another page 2 with more text content"],
        metadata={"/Title": "Test PDF", "/Author": "R2-A Tests"},
    )
    return path


@pytest.fixture
def single_page_text_pdf(tmp_path):
    path = tmp_path / "single.pdf"
    write_text_pdf(path, pages=["Only one page of text"])
    return path


@pytest.fixture
def blank_pdf(tmp_path):
    path = tmp_path / "blank.pdf"
    write_blank_pdf(path, page_count=2)
    return path


@pytest.fixture
def encrypted_pdf(tmp_path):
    path = tmp_path / "enc.pdf"
    write_encrypted_pdf(path, pages=["secret content"], user_password="hunter2")
    return path


@pytest.fixture
def corrupted_pdf(tmp_path):
    path = tmp_path / "corrupt.pdf"
    write_corrupted_pdf(path)
    return path


# ============================================================================
# B. Models / Protocol
# ============================================================================


class TestModelsAndProtocol:
    def test_pdf_inspection_is_frozen(self) -> None:
        ins = PdfInspection(
            file_size_bytes=100,
            page_count=1,
            encrypted=False,
            password_required=False,
            metadata=PdfMetadata(),
            has_extractable_text_estimate=True,
        )
        with pytest.raises((AttributeError, Exception)):
            ins.file_size_bytes = 200  # type: ignore[misc]

    def test_pdf_page_is_frozen(self) -> None:
        page = PdfPage(page_number=1, text="hello")
        with pytest.raises((AttributeError, Exception)):
            page.text = "modified"  # type: ignore[misc]

    def test_pdf_page_1_based(self, parser, text_pdf):
        res = parser.extract(text_pdf)
        assert res.pages[0].page_number == 1
        assert res.pages[1].page_number == 2

    def test_extraction_result_pages_is_tuple(self, parser, text_pdf):
        res = parser.extract(text_pdf)
        assert isinstance(res.pages, tuple)
        assert all(isinstance(p, PdfPage) for p in res.pages)

    def test_inspection_warnings_is_tuple(self, parser, text_pdf):
        ins = parser.inspect(text_pdf)
        assert isinstance(ins.inspection_warnings, tuple)

    def test_metadata_repr_no_absolute_path(self, parser, text_pdf):
        ins = parser.inspect(text_pdf)
        # PdfMetadata and PdfInspection repr must not contain absolute path
        assert "tmp_path" not in repr(ins)
        assert ":\\" not in repr(ins).lower() or "c:" not in repr(ins).lower()

    def test_extraction_result_no_pypdf_object_leak(self, parser, text_pdf):
        res = parser.extract(text_pdf)
        # Walk all attributes recursively — must not find a pypdf PageObject
        text = repr(res)
        assert "PageObject" not in text
        assert "PdfReader" not in text

    def test_parser_protocol_runtime_checkable(self, parser):
        # @runtime_checkable Protocol — isinstance should pass
        assert isinstance(parser, PdfParser)

    def test_parser_protocol_has_required_methods(self):
        # Static check — Protocol declares parser_id, parser_version, inspect,
        # extract, close
        assert hasattr(PdfParser, "parser_id")
        assert hasattr(PdfParser, "parser_version")
        assert hasattr(PdfParser, "inspect")
        assert hasattr(PdfParser, "extract")
        assert hasattr(PdfParser, "close")


# ============================================================================
# C. Inspect
# ============================================================================


class TestInspect:
    def test_single_page(self, parser, single_page_text_pdf):
        ins = parser.inspect(single_page_text_pdf)
        assert ins.page_count == 1
        assert ins.encrypted is False
        assert ins.password_required is False

    def test_multi_page_count(self, parser, text_pdf):
        ins = parser.inspect(text_pdf)
        assert ins.page_count == 2

    def test_file_size_bytes_positive(self, parser, text_pdf):
        ins = parser.inspect(text_pdf)
        assert ins.file_size_bytes > 0

    def test_metadata_extracted(self, parser, text_pdf):
        ins = parser.inspect(text_pdf)
        assert ins.metadata.title == "Test PDF"
        assert ins.metadata.author == "R2-A Tests"

    def test_blank_pdf_has_text_false(self, parser, blank_pdf):
        ins = parser.inspect(blank_pdf)
        assert ins.has_extractable_text_estimate is False

    def test_text_pdf_has_text_true(self, parser, text_pdf):
        ins = parser.inspect(text_pdf)
        assert ins.has_extractable_text_estimate is True

    def test_encrypted_pdf_password_required(self, parser, encrypted_pdf):
        ins = parser.inspect(encrypted_pdf)
        assert ins.encrypted is True
        assert ins.password_required is True
        assert ins.page_count == 0  # cannot probe without password
        assert ins.has_extractable_text_estimate is None

    def test_encrypted_pdf_has_warning(self, parser, encrypted_pdf):
        ins = parser.inspect(encrypted_pdf)
        assert any("encrypted" in w for w in ins.inspection_warnings)

    def test_corrupted_pdf_raises_invalid(self, parser, corrupted_pdf):
        with pytest.raises(InvalidPdf):
            parser.inspect(corrupted_pdf)

    def test_nonexistent_path_raises(self, parser, tmp_path):
        with pytest.raises(PdfFileNotFound):
            parser.inspect(tmp_path / "does_not_exist.pdf")

    def test_directory_path_raises_not_a_file(self, parser, tmp_path):
        with pytest.raises((PdfNotAFile, PdfParserError)):
            parser.inspect(tmp_path)

    def test_file_handle_released(self, parser, text_pdf):
        # On Windows, an unclosed file handle would block deletion.
        parser.inspect(text_pdf)
        # Should be deletable without error
        text_pdf.unlink()

    def test_consecutive_inspect_stable(self, parser, text_pdf):
        a = parser.inspect(text_pdf)
        b = parser.inspect(text_pdf)
        assert a.page_count == b.page_count
        assert a.file_size_bytes == b.file_size_bytes
        assert a.has_extractable_text_estimate == b.has_extractable_text_estimate


# ============================================================================
# D. Extract
# ============================================================================


class TestExtract:
    def test_single_page_text(self, parser, single_page_text_pdf):
        res = parser.extract(single_page_text_pdf)
        assert len(res.pages) == 1
        assert "Only one page" in res.pages[0].text

    def test_multi_page_order(self, parser, text_pdf):
        res = parser.extract(text_pdf)
        assert len(res.pages) == 2
        assert "Hello World page 1" in res.pages[0].text
        assert "Another page 2" in res.pages[1].text

    def test_page_numbers_sequential_1_based(self, parser, text_pdf):
        res = parser.extract(text_pdf)
        numbers = [p.page_number for p in res.pages]
        assert numbers == [1, 2]

    def test_parser_id_and_version_in_result(self, parser, text_pdf):
        res = parser.extract(text_pdf)
        assert res.parser_id == "pypdf"
        assert res.parser_version == parser.parser_version

    def test_blank_page_returns_empty_string_not_none(self, parser, blank_pdf):
        res = parser.extract(blank_pdf)
        for page in res.pages:
            assert page.text == ""
            assert isinstance(page.text, str)

    def test_crlf_normalized(self, parser, tmp_path):
        # Inject CRLF via raw text — fixture helper escapes newlines to space,
        # but if pypdf returns \r\n in extraction, adapter should normalize.
        # Test by checking adapter._normalize_text directly.
        from pi_agent_core_py.web.knowledge.pypdf_parser import PypdfParser
        assert PypdfParser._normalize_text("a\r\nb\rc") == "a\nb\nc"

    def test_nul_bytes_stripped(self, parser):
        from pi_agent_core_py.web.knowledge.pypdf_parser import PypdfParser
        assert PypdfParser._normalize_text("a\x00b") == "ab"

    def test_none_text_becomes_empty(self, parser):
        from pi_agent_core_py.web.knowledge.pypdf_parser import PypdfParser
        assert PypdfParser._normalize_text(None) == ""

    def test_encrypted_pdf_rejected(self, parser, encrypted_pdf):
        with pytest.raises(PdfPasswordRequired):
            parser.extract(encrypted_pdf)

    def test_corrupted_pdf_rejected(self, parser, corrupted_pdf):
        with pytest.raises(InvalidPdf):
            parser.extract(corrupted_pdf)

    def test_nonexistent_rejected(self, parser, tmp_path):
        with pytest.raises(PdfFileNotFound):
            parser.extract(tmp_path / "nope.pdf")

    def test_source_pdf_not_modified(self, parser, text_pdf):
        sha_before = file_sha256(text_pdf)
        parser.inspect(text_pdf)
        parser.extract(text_pdf)
        sha_after = file_sha256(text_pdf)
        assert sha_before == sha_after

    def test_close_idempotent(self, parser):
        parser.close()
        parser.close()  # second close must not raise

    def test_extract_after_close_raises(self, parser, text_pdf):
        parser.close()
        with pytest.raises(PdfParserError):
            parser.extract(text_pdf)

    def test_consecutive_extract_stable(self, parser, text_pdf):
        a = parser.extract(text_pdf)
        b = parser.extract(text_pdf)
        assert len(a.pages) == len(b.pages)
        for pa, pb in zip(a.pages, b.pages, strict=True):
            assert pa.text == pb.text


# ============================================================================
# E. Security / Boundary
# ============================================================================


class TestSecurityBoundary:
    def test_no_network_imports_in_adapter(self) -> None:
        """Adapter module must not import any network / OCR / model / LLM libs."""
        from pi_agent_core_py.web.knowledge import pypdf_parser

        text = Path(pypdf_parser.__file__).read_text(encoding="utf-8")
        forbidden = [
            "import requests",
            "from requests",
            "import httpx",
            "from httpx",
            "import urllib",
            "from urllib",
            "import aiohttp",
            "from aiohttp",
            "import openai",
            "from openai",
            "import anthropic",
            "from anthropic",
            "google.genai",
            "import torch",
            "from torch",
            "import transformers",
            "from transformers",
            "import surya",
            "from surya",
            "import fitz",
            "from fitz",
            "import pymupdf",
            "from pymupdf",
            "huggingface_hub",
            "huggingface-hub",
        ]
        for token in forbidden:
            assert token not in text, (
                f"forbidden import {token!r} found in pypdf_parser.py"
            )

    def test_no_markdown_generation(self, parser, text_pdf):
        res = parser.extract(text_pdf)
        # Result must not contain markdown artifacts (frontmatter, headings,
        # page markers). Those are R2-B's job.
        for page in res.pages:
            assert "<!-- page:" not in page.text
            assert "---\n" not in page.text[:50]  # no YAML frontmatter
            assert not page.text.startswith("# ")

    def test_error_messages_no_absolute_path(self, parser, tmp_path):
        """All error messages must omit absolute paths."""
        missing = tmp_path / "nope.pdf"
        try:
            parser.inspect(missing)
        except PdfParserError as e:
            msg = str(e)
            assert str(tmp_path) not in msg
            assert ":\\" not in msg.lower() or "c:" not in msg.lower()
        else:
            pytest.fail("expected PdfParserError")

    def test_error_messages_no_pypdf_traceback(self, parser, corrupted_pdf):
        try:
            parser.inspect(corrupted_pdf)
        except InvalidPdf as e:
            msg = str(e)
            # No pypdf internal class names in message
            assert "PdfReader" not in msg
            assert "traceback" not in msg.lower()

    def test_pypdf_only_imported_in_adapter_module(self) -> None:
        """Walk all .py in src except pypdf_parser.py — none should import pypdf."""
        import re
        from pathlib import Path as P

        src_root = P(__file__).resolve().parent.parent / "src"
        offenders: list[str] = []
        for py in src_root.rglob("*.py"):
            if py.name == "pypdf_parser.py":
                continue
            text = py.read_text(encoding="utf-8", errors="ignore")
            if re.search(r"^\s*(import pypdf|from pypdf)", text, re.MULTILINE):
                offenders.append(str(py.relative_to(src_root)))
        assert offenders == [], (
            f"pypdf must only be imported in pypdf_parser.py; found in: {offenders}"
        )


# ============================================================================
# Optional dependency unavailable (simulated via mock)
# ============================================================================


class TestOptionalDependencyMissing:
    def test_pypdf_missing_raises_unavailable(self, monkeypatch):
        """Simulate pypdf not installed — PypdfParser() must raise
        PdfParserUnavailable, not ImportError."""
        # Hide pypdf from importlib
        real_import = __import__

        def fake_import(name, *args, **kwargs):
            if name == "pypdf" or name.startswith("pypdf."):
                raise ImportError(f"simulated: no module named {name!r}")
            return real_import(name, *args, **kwargs)

        monkeypatch.setattr("builtins.__import__", fake_import)
        with pytest.raises(PdfParserUnavailable):
            PypdfParser()

    def test_safe_error_code_on_unavailable(self, monkeypatch):
        real_import = __import__

        def fake_import(name, *args, **kwargs):
            if name == "pypdf" or name.startswith("pypdf."):
                raise ImportError("simulated")
            return real_import(name, *args, **kwargs)

        monkeypatch.setattr("builtins.__import__", fake_import)
        try:
            PypdfParser()
        except PdfParserUnavailable as e:
            assert e.safe_error_code == "pdf_parser_unavailable"
            # Message must not contain site-packages path / pip hint with paths
            assert "site-packages" not in str(e)


# ============================================================================
# Page-level failure (option A: terminate whole extract)
# ============================================================================


class TestPageLevelFailure:
    def test_page_extract_failure_terminates_whole_extract(
        self, parser, text_pdf
    ):
        """Per P2-R2-A §17 option A — single page failure must terminate the
        whole extract (no silent missing pages)."""
        from pypdf import PageObject

        # Patch the second page's extract_text to raise
        original = PageObject.extract_text

        call_count = {"n": 0}

        def boom(self, *args, **kwargs):
            call_count["n"] += 1
            if call_count["n"] == 2:
                raise RuntimeError("simulated page extract failure")
            return original(self, *args, **kwargs)

        with patch.object(PageObject, "extract_text", boom):
            with pytest.raises(PdfPageExtractFailed):
                parser.extract(text_pdf)


# ============================================================================
# Constants / helper sanity
# ============================================================================


class TestConstants:
    def test_text_estimate_sample_count_is_small(self):
        assert TEXT_ESTIMATE_SAMPLE_COUNT <= 5

    def test_text_estimate_min_chars_positive(self):
        assert TEXT_ESTIMATE_MIN_CHARS_PER_PAGE > 0

    def test_metadata_max_length(self):
        assert MAX_METADATA_VALUE_LENGTH == 500

    def test_truncate_metadata_value_strips_control_chars(self):
        assert truncate_metadata_value("hello\x00world") == "helloworld"

    def test_truncate_metadata_value_handles_none(self):
        assert truncate_metadata_value(None) is None

    def test_truncate_metadata_value_truncates_long(self):
        long = "x" * (MAX_METADATA_VALUE_LENGTH + 100)
        result = truncate_metadata_value(long)
        assert result is not None
        assert len(result) == MAX_METADATA_VALUE_LENGTH


# ============================================================================
# Fixture integrity
# ============================================================================


class TestFixtureIntegrity:
    """Verify fixtures generated by _pdf_fixture_factory behave as expected —
    critical because all parser tests depend on these."""

    def test_text_pdf_has_text_per_page(self, tmp_path):
        path = tmp_path / "f.pdf"
        write_text_pdf(path, pages=["page one text", "page two text"])
        p = PypdfParser()
        res = p.extract(path)
        assert "page one text" in res.pages[0].text
        assert "page two text" in res.pages[1].text

    def test_blank_pdf_has_no_text(self, tmp_path):
        path = tmp_path / "b.pdf"
        write_blank_pdf(path, page_count=1)
        p = PypdfParser()
        res = p.extract(path)
        assert res.pages[0].text == ""

    def test_encrypted_pdf_is_encrypted(self, tmp_path):
        path = tmp_path / "e.pdf"
        write_encrypted_pdf(path, pages=["secret"], user_password="pw")
        p = PypdfParser()
        ins = p.inspect(path)
        assert ins.encrypted is True

    def test_corrupted_pdf_is_invalid(self, tmp_path):
        path = tmp_path / "c.pdf"
        write_corrupted_pdf(path)
        p = PypdfParser()
        with pytest.raises(InvalidPdf):
            p.inspect(path)


# ============================================================================
# Public symbols
# ============================================================================


__all__: list[str] = [
    "TestConstants",
    "TestExtract",
    "TestFixtureIntegrity",
    "TestInspect",
    "TestModelsAndProtocol",
    "TestOptionalDependencyMissing",
    "TestPageLevelFailure",
    "TestSecurityBoundary",
]


# Suppress unused-symbol lint for fixtures/helpers used by other test modules.
_unused: tuple[Any, ...] = (
    hashlib,
    sys,
)
