"""New page-centric LLM Wiki persistence package.

The legacy chunk-RAG implementation remains isolated under ``web.knowledge``
until the explicit retirement cutover.  This package never imports it.
"""

from .errors import (
    LegacyRetirementError,
    WikiErrorCode,
    WikiMirrorError,
    WikiPathError,
    WikiSchemaError,
    WikiStoreError,
)
from .files import WikiFileStore
from .html_parser import (
    HTML_PARSER_VERSION,
    HtmlEmbeddedImage,
    HtmlParseResult,
    HtmlParserLimits,
    parse_single_html,
)
from .ingestion import (
    HTML_ARTIFACT_SCHEMA,
    WikiIngestionLimits,
    WikiIngestionService,
    WikiParseOutcome,
)
from .legacy import retire_legacy_knowledge
from .models import (
    WIKI_LEGACY_MANIFEST_SCHEMA,
    WIKI_SCHEMA_VERSION,
    WIKI_SELECTED_PARSE_SCHEMA,
    WIKI_SPACE_MANIFEST_SCHEMA,
    WikiArtifact,
    WikiArtifactKind,
    WikiJob,
    WikiJobKind,
    WikiJobStatus,
    WikiLegacyBackupReceipt,
    WikiMirrorRepairReport,
    WikiParseAttempt,
    WikiParseAttemptState,
    WikiParseMode,
    WikiParseRevision,
    WikiSelectedParsePointer,
    WikiSource,
    WikiSourceMimeType,
    WikiSourceStatus,
    WikiSpace,
    WikiSpaceManifest,
    WikiSpaceStatus,
    validate_artifact_id,
    validate_job_id,
    validate_parse_attempt_id,
    validate_parse_revision_id,
    validate_source_id,
    validate_space_id,
)
from .store import WIKI_APPLICATION_ID, LegacyPolicy, WikiStore
from .worker import WikiIngestionWorkerManager

__all__ = [
    "WIKI_LEGACY_MANIFEST_SCHEMA",
    "WIKI_SCHEMA_VERSION",
    "WIKI_SELECTED_PARSE_SCHEMA",
    "WIKI_SPACE_MANIFEST_SCHEMA",
    "HTML_ARTIFACT_SCHEMA",
    "HTML_PARSER_VERSION",
    "HtmlEmbeddedImage",
    "HtmlParseResult",
    "HtmlParserLimits",
    "LegacyRetirementError",
    "LegacyPolicy",
    "WIKI_APPLICATION_ID",
    "WikiErrorCode",
    "WikiArtifact",
    "WikiArtifactKind",
    "WikiLegacyBackupReceipt",
    "WikiJob",
    "WikiJobKind",
    "WikiJobStatus",
    "WikiIngestionLimits",
    "WikiIngestionService",
    "WikiIngestionWorkerManager",
    "WikiFileStore",
    "WikiMirrorError",
    "WikiMirrorRepairReport",
    "WikiParseAttempt",
    "WikiParseAttemptState",
    "WikiParseMode",
    "WikiParseRevision",
    "WikiPathError",
    "WikiParseOutcome",
    "WikiSchemaError",
    "WikiSource",
    "WikiSourceMimeType",
    "WikiSourceStatus",
    "WikiSelectedParsePointer",
    "WikiSpace",
    "WikiSpaceManifest",
    "WikiSpaceStatus",
    "WikiStoreError",
    "WikiStore",
    "retire_legacy_knowledge",
    "parse_single_html",
    "validate_artifact_id",
    "validate_job_id",
    "validate_parse_attempt_id",
    "validate_parse_revision_id",
    "validate_source_id",
    "validate_space_id",
]
