"""New page-centric LLM Wiki persistence package.

The legacy chunk-RAG implementation remains isolated under ``web.knowledge``
until the explicit retirement cutover.  This package never imports it.
"""

from .changes import WikiChangeSetService
from .conversations import WikiConversationService
from .errors import (
    LegacyRetirementError,
    WikiErrorCode,
    WikiMirrorError,
    WikiPathError,
    WikiSchemaError,
    WikiStoreError,
)
from .files import WikiFileStore
from .fts import MAX_WIKI_FTS_QUERY_CHARS, compile_wiki_fts_query
from .html_parser import (
    HTML_PARSER_VERSION,
    HtmlEmbeddedImage,
    HtmlParseResult,
    HtmlParserLimits,
    parse_single_html,
)
from .ingestion import (
    HTML_ARTIFACT_SCHEMA,
    WikiIngestionLimits,
    WikiIngestionService,
    WikiParseOutcome,
)
from .legacy import retire_legacy_knowledge
from .models import (
    WIKI_LEGACY_MANIFEST_SCHEMA,
    WIKI_SCHEMA_VERSION,
    WIKI_SELECTED_PARSE_SCHEMA,
    WIKI_SPACE_MANIFEST_SCHEMA,
    WikiArtifact,
    WikiArtifactKind,
    WikiChangeSet,
    WikiChangeSetItem,
    WikiChangeSetOperationKind,
    WikiConversation,
    WikiConversationStatus,
    WikiEdge,
    WikiGraphEdge,
    WikiGraphNode,
    WikiGraphNodeKind,
    WikiGraphRelationType,
    WikiGraphSnapshot,
    WikiJob,
    WikiJobKind,
    WikiJobStatus,
    WikiLegacyBackupReceipt,
    WikiMirrorRepairReport,
    WikiPage,
    WikiPageAuthorKind,
    WikiPageProposal,
    WikiPageProposalKind,
    WikiPageRevision,
    WikiPageSearchResult,
    WikiPageStatus,
    WikiParseAttempt,
    WikiParseAttemptState,
    WikiParseMode,
    WikiParseRevision,
    WikiRelationType,
    WikiSelectedParsePointer,
    WikiSource,
    WikiSourceMimeType,
    WikiSourceStatus,
    WikiSourceSummaryContent,
    WikiSourceSummaryDraft,
    WikiSpace,
    WikiSpaceManifest,
    WikiSpaceStatus,
    WikiSummaryKeyPoint,
    WikiSummaryTopic,
    validate_artifact_id,
    validate_change_set_id,
    validate_change_set_item_id,
    validate_conversation_id,
    validate_edge_id,
    validate_job_id,
    validate_page_id,
    validate_page_proposal_id,
    validate_page_revision_id,
    validate_parse_attempt_id,
    validate_parse_revision_id,
    validate_source_id,
    validate_space_id,
    validate_summary_id,
)
from .pages import WikiEntryPageService
from .store import WIKI_APPLICATION_ID, LegacyPolicy, WikiStore
from .summary import (
    WIKI_SUMMARY_PROMPT_REVISION,
    CoreAgentWikiSummaryAgent,
    WikiSummaryAgent,
    WikiSummaryAgentResponse,
    WikiSummaryLimits,
    WikiSummaryService,
)
from .worker import WikiIngestionWorkerManager

__all__ = [
    "WIKI_LEGACY_MANIFEST_SCHEMA",
    "WIKI_SCHEMA_VERSION",
    "WIKI_SELECTED_PARSE_SCHEMA",
    "WIKI_SPACE_MANIFEST_SCHEMA",
    "WIKI_SUMMARY_PROMPT_REVISION",
    "HTML_ARTIFACT_SCHEMA",
    "HTML_PARSER_VERSION",
    "HtmlEmbeddedImage",
    "HtmlParseResult",
    "HtmlParserLimits",
    "LegacyRetirementError",
    "LegacyPolicy",
    "WIKI_APPLICATION_ID",
    "MAX_WIKI_FTS_QUERY_CHARS",
    "WikiErrorCode",
    "WikiArtifact",
    "WikiArtifactKind",
    "WikiChangeSet",
    "WikiChangeSetItem",
    "WikiChangeSetOperationKind",
    "WikiChangeSetService",
    "WikiConversation",
    "WikiConversationService",
    "WikiConversationStatus",
    "WikiEdge",
    "WikiGraphEdge",
    "WikiGraphNode",
    "WikiGraphNodeKind",
    "WikiGraphRelationType",
    "WikiGraphSnapshot",
    "WikiLegacyBackupReceipt",
    "WikiJob",
    "WikiJobKind",
    "WikiJobStatus",
    "WikiIngestionLimits",
    "WikiIngestionService",
    "WikiIngestionWorkerManager",
    "WikiFileStore",
    "WikiMirrorError",
    "WikiMirrorRepairReport",
    "WikiPage",
    "WikiPageAuthorKind",
    "WikiParseAttempt",
    "WikiParseAttemptState",
    "WikiParseMode",
    "WikiParseRevision",
    "WikiPageProposal",
    "WikiPageProposalKind",
    "WikiPageRevision",
    "WikiPageSearchResult",
    "WikiPageStatus",
    "WikiPathError",
    "WikiParseOutcome",
    "WikiSchemaError",
    "WikiSource",
    "WikiSourceSummaryContent",
    "WikiSourceSummaryDraft",
    "WikiSummaryKeyPoint",
    "WikiSummaryTopic",
    "WikiSourceMimeType",
    "WikiSourceStatus",
    "WikiSelectedParsePointer",
    "WikiSpace",
    "WikiSpaceManifest",
    "WikiSpaceStatus",
    "WikiRelationType",
    "WikiStoreError",
    "WikiStore",
    "WikiEntryPageService",
    "CoreAgentWikiSummaryAgent",
    "WikiSummaryAgent",
    "WikiSummaryAgentResponse",
    "WikiSummaryLimits",
    "WikiSummaryService",
    "retire_legacy_knowledge",
    "parse_single_html",
    "compile_wiki_fts_query",
    "validate_artifact_id",
    "validate_change_set_id",
    "validate_change_set_item_id",
    "validate_conversation_id",
    "validate_edge_id",
    "validate_job_id",
    "validate_page_id",
    "validate_parse_attempt_id",
    "validate_parse_revision_id",
    "validate_page_proposal_id",
    "validate_page_revision_id",
    "validate_source_id",
    "validate_space_id",
    "validate_summary_id",
]
