"""Isolated, provider-neutral contracts for LLM Wiki document parsing.

This package intentionally does not import pi-agent, concrete PDF parser
runtimes, FastAPI, or any process/container SDK. Real parser runtimes are
optional workers outside the main application dependency graph.
"""

from .contract_v2 import (
    PARSER_ARTIFACT_SCHEMA_V2,
    PARSER_CONTRACT_VERSION_V2,
    ParserArtifactFileV2,
    ParserArtifactKindV2,
    ParserArtifactManifestV2,
    ParserArtifactReceiptV2,
    ParserAttemptEvidence,
    ParserAttemptStateV2,
    ParserBoundingBox,
    ParserCapabilitiesV2,
    ParserEngineName,
    ParserImageMimeTypeV2,
    ParserJobHandleV2,
    ParserJobPhaseV2,
    ParserJobSpecV2,
    ParserJobStateV2,
    ParserJobStatusV2,
    ParserLicenseModeV2,
    ParserParsedAsset,
    ParserParsedDocument,
    ParserParsedPage,
    ParserPreflightReport,
    ParserPresetName,
    ParserProbeV2,
    ParserProviderV2Name,
    ParserQualityFailureCode,
    ParserQualityMetrics,
    ParserQualityReport,
    ParserRequestedMode,
    ParserRouteDecision,
    ParserRouteReason,
    ParserRoutingConfigIdentity,
    ParserSourceSpan,
    canonical_markdown_v2,
    canonical_preflight_sha256,
)
from .errors import ParserError, ParserErrorCode
from .fake import FakeParserImage, FakeParserOutput, FakeParserProvider
from .fake_v2 import (
    FakeAttemptOutcomeV2,
    FakeDualPdfParserProvider,
    FakeParserAssetV2,
    FakeParserDocumentV2,
    FakeParserScenarioV2,
    FakePreflightProfileV2,
)
from .models import (
    PARSER_ARTIFACT_SCHEMA,
    PARSER_CONTRACT_VERSION,
    ParserArtifactFile,
    ParserArtifactKind,
    ParserArtifactManifest,
    ParserArtifactReceipt,
    ParserCapabilities,
    ParserImageMimeType,
    ParserJobHandle,
    ParserJobSpec,
    ParserJobState,
    ParserJobStatus,
    ParserLicenseMode,
    ParserLimits,
    ParserMediaType,
    ParserMode,
    ParserProbe,
    ParserProviderName,
    ParserSourceSpec,
    validate_artifact_path,
)
from .provider import ParserProvider
from .provider_v2 import ParserProviderV2

__all__ = [
    "PARSER_ARTIFACT_SCHEMA",
    "PARSER_ARTIFACT_SCHEMA_V2",
    "PARSER_CONTRACT_VERSION",
    "PARSER_CONTRACT_VERSION_V2",
    "FakeParserImage",
    "FakeParserOutput",
    "FakeParserProvider",
    "FakeAttemptOutcomeV2",
    "FakeDualPdfParserProvider",
    "FakeParserAssetV2",
    "FakeParserDocumentV2",
    "FakeParserScenarioV2",
    "FakePreflightProfileV2",
    "ParserArtifactFile",
    "ParserArtifactFileV2",
    "ParserArtifactKind",
    "ParserArtifactKindV2",
    "ParserArtifactManifest",
    "ParserArtifactManifestV2",
    "ParserArtifactReceipt",
    "ParserArtifactReceiptV2",
    "ParserAttemptEvidence",
    "ParserAttemptStateV2",
    "ParserBoundingBox",
    "ParserCapabilities",
    "ParserCapabilitiesV2",
    "ParserEngineName",
    "ParserError",
    "ParserErrorCode",
    "ParserImageMimeType",
    "ParserImageMimeTypeV2",
    "ParserJobHandle",
    "ParserJobHandleV2",
    "ParserJobPhaseV2",
    "ParserJobSpec",
    "ParserJobSpecV2",
    "ParserJobState",
    "ParserJobStateV2",
    "ParserJobStatus",
    "ParserJobStatusV2",
    "ParserLicenseMode",
    "ParserLicenseModeV2",
    "ParserLimits",
    "ParserMediaType",
    "ParserMode",
    "ParserProbe",
    "ParserProbeV2",
    "ParserProvider",
    "ParserProviderV2",
    "ParserProviderV2Name",
    "ParserProviderName",
    "ParserParsedAsset",
    "ParserParsedDocument",
    "ParserParsedPage",
    "ParserPreflightReport",
    "ParserPresetName",
    "ParserQualityFailureCode",
    "ParserQualityMetrics",
    "ParserQualityReport",
    "ParserRequestedMode",
    "ParserRouteDecision",
    "ParserRouteReason",
    "ParserRoutingConfigIdentity",
    "ParserSourceSpec",
    "ParserSourceSpan",
    "canonical_markdown_v2",
    "canonical_preflight_sha256",
    "validate_artifact_path",
]
